### ISSUE TITLE
Manage Drivers [delete]

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#128]
Can't delete drivers on Manage Drivers screen (404 not found)

**Comment by AlexEdimensionz** [comment]
Yup.. I know
I need to know whether to delete the driver or mark them as inactive. 
and what should i do with their marked jobs

A


e-dimensionz Inc.
Tel: 226.444.8466
Mob: 226.338.8980
http://e-dimensionz.com

**Comment by melissa-edimensionz** [comment]
Probably marking as inactive would be best & safest toute

**Comment by TroyManary** [comment]
I agree with Melissa.  Mark it as inactive.

When it is inactive:
-------------------------
* Do not display it on the Manage Driver's page.
* Any outstanding service calls should expire as normal.  Deleting an active driver is equivalent to ignoring a service call - not a good thing to do, but we can't stop them from doing stupid things.
* Do not allow the same username to be created again - if an operator tries to re-use it, they will need to contact us to manually update the database and then we can ensure it works OK.

**Comment by AlexEdimensionz** [comment]
Done

**Comment by TroyManary** [comment]
It is mostly working.
I deleted the driver and then checked the user database - the account still exists (as expected).
Tried logging in and it let me into the system but displayed an Error.
It should not allow a deleted driver to login.
![image](https://cloud.githubusercontent.com/assets/10308999/10847126/af3f1f92-7eea-11e5-9023-e1fc13d1e2a7.png)

**Comment by AlexEdimensionz** [comment]
It just marks the driver as inactive but the login account doesn't get  
disabled (will add that now)

e-dimensionz Inc.
Tel: 226.444.8466
Mob: 226.338.8980
http://e-dimensionz.com

**Comment by AlexEdimensionz** [comment]
BTW this is done and accounts are blocked  when "Deleted"
