### ISSUE TITLE
Driver Registration: Activation Link Failed

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#140]
I created an Operator Account and then added 2 drivers.
I received the emails for the 2 drivers (see below) but when I clicked the activation links, they failed and this was displayed:
![image](https://cloud.githubusercontent.com/assets/10308999/10830876/7ebaef0a-7e58-11e5-8779-a7eac5119e61.png)
![image](https://cloud.githubusercontent.com/assets/10308999/10830891/925b9c30-7e58-11e5-9023-5c5e946f4c9f.png)

**Comment by gustave-eplow** [comment]
This also happened to me.
Shared this with Alex when we spoke earlier and he thought it was because
I'd clicked the sign-up link before.
This appears to require closer attention.
Gustave

**Comment by AlexEdimensionz** [comment]
Fixed activation link issue

**Comment by TroyManary** [comment]
Still getting the error message:
![capture](https://cloud.githubusercontent.com/assets/10308999/10846901/6a9e5958-7ee9-11e5-89c8-a9c943aa9983.JPG)

![image](https://cloud.githubusercontent.com/assets/10308999/10846880/3f715154-7ee9-11e5-9bdb-db974c56cabd.png)

**Comment by AlexEdimensionz** [comment]
That last screenshot you sent me is linked to an expired activation string. I think you may have removed and re-added that account. The current activation hash for tmanary.66@gmail.com is 
fa283c325a58245f66d0313357eacfc0

**Comment by TroyManary** [comment]
I have tried several times and still can't get the Driver Activation to work.
I used an account that I have never used before and it still doesn't work.
Here is the e-mail:
![capture](https://cloud.githubusercontent.com/assets/10308999/10857653/bb0c3d7e-7f25-11e5-893d-17691448994f.JPG)

**Comment by AlexEdimensionz** [comment]
Can you call me on skype?
A

**Comment by AlexEdimensionz** [comment]
Done
