### ISSUE TITLE
Driver Service Area is not Saved

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#141]
I created an Operator account and added 2 drivers, each with a service area.
When I go back to 'Manage Drivers' and 'edit service areas' they do not appear on the map.

I noticed that when I 'save' the service area, an error message is briefly displayed in top left:
    function storemap() does not exist

**Comment by AlexEdimensionz** [comment]
Do a hard refresh (SHIFT+Refresh) - the js files on this page have changed, you might be hitting cached code. the storemap error was fixed as well before

**Comment by TroyManary** [comment]
It behaves different now but still not as expected.
When I click 'save' I get a pop up asking for a name:
![image](https://cloud.githubusercontent.com/assets/10308999/10833915/a71adb96-7e6b-11e5-80a9-697d22ac0097.png)

**Comment by AlexEdimensionz** [comment]
Actually i'm adding a feature to save a name for a map for the dropdown. I will update this ticket when it's done
