### ISSUE TITLE
Consumer- Request Service Formatting issue

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#75]
found on eplow.staging0.com in Safari on iPad mini

1.Customer Login
2.Clicked on "schedule a new service call"
3. On the "request service" page there is an overlap in the province and postal code fields.  The postal code text queue is cut off as well
4. Page also indicates error occured

See Image

![img_0186](https://cloud.githubusercontent.com/assets/13750782/10064075/c094cfb8-6242-11e5-9c3d-e4a36ec9969e.PNG)

**Comment by melissa-edimensionz** [comment]
Fixed.

**Comment by rachelle-eplow** [comment]
cannot verify at this time

**Comment by rachelle-eplow** [comment]
error still occurs in the page.
![error](https://cloud.githubusercontent.com/assets/13750782/10551754/e7475f54-741c-11e5-995c-6cac6227609f.JPG)

**Comment by melissa-edimensionz** [comment]
@AlexEdimensionz 
2 issues in ticket. Overlap should be fixed, just error at top of page. (See screenshot above this message). There is another ticket for this, but assigned this to you to close when fixed.
